import ApplicationServices
import AppKit

@MainActor
enum TextInjector {
    /// Clipboard backup waiting to be restored after our paste
    private struct PendingRestore {
        let original: String?
        let changeCount: Int
        let generation: Int
    }
    
    private static var pendingRestore: PendingRestore?
    private static var generation = 0
    
    static func inject(text: String) {
        let pasteboard = NSPasteboard.general
        
        // 1. Back up current content (Best effort: Strings only for now)
        // If a previous paste's restore is still pending and the clipboard still holds our own text,
        // keep that paste's backup - otherwise back-to-back dictations would "restore" our transient text.
        let original: String?
        if let pending = pendingRestore, pasteboard.changeCount == pending.changeCount {
            original = pending.original
        } else {
            original = pasteboard.string(forType: .string)
        }
        
        // 2. Set new text with Transient metadata
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        
        // Mark as transient/autogenerated so clipboard managers (Maccy, Paste, etc.) ignore it
        // Note: Using raw string values to avoid type system issues if not defined in older SDKs
        pasteboard.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.transient"))
        pasteboard.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        
        generation += 1
        let restore = PendingRestore(original: original, changeCount: pasteboard.changeCount, generation: generation)
        pendingRestore = restore
        
        // 3. Simulate Cmd+V
        simulatePaste()
        
        // 4. Restore original content after a delay
        // We wait long enough for the system paste to trigger (Cmd+V), then verify we haven't been overwritten externally
        Task { @MainActor in
            try? await Task.sleep(nanoseconds: 600_000_000) // 600ms
            
            // A newer paste owns the restore now
            guard TextInjector.pendingRestore?.generation == restore.generation else { return }
            TextInjector.pendingRestore = nil
            
            // Only restore if the clipboard hasn't changed since we set it
            guard pasteboard.changeCount == restore.changeCount else { return }
            pasteboard.clearContents()
            if let previous = restore.original {
                pasteboard.setString(previous, forType: .string)
            }
        }
    }
    
    private static func simulatePaste() {
        // Create a source that mimics hardware input
        guard let source = CGEventSource(stateID: .hidSystemState) else { return }
        
        // Command key down
        let cmdDown = CGEvent(keyboardEventSource: source, virtualKey: 0x37, keyDown: true) // kVK_Command
        cmdDown?.flags = .maskCommand
        
        // V key down
        let vDown = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: true) // kVK_ANSI_V
        vDown?.flags = .maskCommand
        
        // V key up
        let vUp = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: false)
        vUp?.flags = .maskCommand
        
        // Command key up
        let cmdUp = CGEvent(keyboardEventSource: source, virtualKey: 0x37, keyDown: false)
        cmdUp?.flags = [] // Clear flags on release
        
        // Post events with brief delays to play nice with system event queue
        cmdDown?.post(tap: .cghidEventTap)
        vDown?.post(tap: .cghidEventTap)
        vUp?.post(tap: .cghidEventTap)
        cmdUp?.post(tap: .cghidEventTap)
    }
}
